### ISSUE TITLE
Modules entry missing error

### ISSUE THREAD

**Issue by geiszla** [smooth-code/loadable-components#119]
I set up everything that's written in the README regarding server-side rendering, however when I try to request a page on the server, it fails with the error:

> (node:9040) UnhandledPromiseRejectionWarning: Error: loadable-components: modules entry is missing, you are probably missing `loadable-components/babel` in your Babel config.
>     at C:\Users\Username\Desktop\RUOut\node_modules\loadable-components\dist\loadable-components.server.cjs.js:186:17
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:189:7)
> (node:9040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:9040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The `.babelrc` plugins setup looks like the following:
```json
{
   "plugins": [
           ["@babel/plugin-proposal-decorators", { "decoratorsBeforeExport": false }],
           "@babel/plugin-proposal-class-properties",
           "loadable-components/babel",
           "dynamic-import-node",
           ["@babel/plugin-transform-runtime", {
               "regenerator": true
           }]
       ]
}
```

Package versions:
- Node: `v8.12.0`
- webpack: `4.19.1`
- webpack-cli: `3.1.1`
- @babel/core: `7.1.0`
- babel-loader: `8.0.2`
- loadable-components: `2.2.3`

**Comment by geiszla** [comment]
Can this be a problem with Babel 7?

**Comment by geiszla** [comment]
So I was using `react-loadable` for a while, because I couldn't make this work. Now I came back again, and tried to switch from `react-loadable` to `loadable-components`, and it worked without any issues. It must have been something I messed up earlier, but I don't know what that is anymore. Anyways, I will close this now, but feel free to reopen if someone has the same problem.
