### ISSUE TITLE
react-router@next issue with SSR

### ISSUE THREAD

**Issue by metsavaht** [smooth-code/loadable-components#121]
I tried to use `loadable-components@2.2.3` with `react-router@4.4.0-beta.3`, `react-router-dom@4.4.0-beta.3` and `react-router-config@4.4.0-beta.3`.

SSR setup is based on `razzle` and `koa`.

This results in error `Invariant Violation: You should not use <Switch> outside a <Router>`

Stacktrace:
```
Invariant Violation: You should not use <Switch> outside a <Router>
      at invariant (../app/node_modules/react-router/cjs/react-router.js:847:15)
      at Object.children (../app/node_modules/react-router/cjs/react-router.js:2828:23)
      at children (../app/node_modules/loadable-components/src/server/index.js:115:37)
      at walkTree (../app/node_modules/loadable-components/dist/loadable-components.server.cjs.js:134:11)
      at ../app/node_modules/loadable-components/dist/loadable-components.server.cjs.js:159:13
      at forEachSingleChild (../app/node_modules/react/cjs/react.development.js:1176:8)
      at traverseAllChildrenImpl (../app/node_modules/react/cjs/react.development.js:1080:5)
      at traverseAllChildren (../app/node_modules/react/cjs/react.development.js:1151:10)
      at Object.forEachChildren [as forEach] (../app/node_modules/react/cjs/react.development.js:1196:3)
      at forEach (../app/node_modules/loadable-components/src/server/index.js:122:24)
```

**Comment by theKashey** [comment]
Just dont use Switch outside of the Router? 
Sorry, but the problem is not quite clear.

**Comment by metsavaht** [comment]
The problem seems to occur inside `loadable-components/server` `getLoadableState`.

This is what my ssr app render looks like, `app` is used with `getLoadableState`.
```
const app = (
            <Provider store={store}>
                <StaticRouter context={context} location={ctx.url}>
                    {renderRoutes(routes)}
                </StaticRouter>
            </Provider>
        );

const loadableState = await getLoadableState(app); // <--- this is where it fails
const markup = renderToString(app);
```

And `routes` look something like this.
`App` is using `{renderRoutes(route.routes)}` to render correct matching route
```
const Home = loadable(() => import('views/Home'));
const routes = [
    {
        component: App,
        routes: [{
            path: '/',
            exact: true,
            component: Home,
        }]
    }
];
```

**Comment by theKashey** [comment]
So problem should be somewhere within `renderRoutes`

**Comment by metsavaht** [comment]
I'm an idiot. messed up one of the exports and issue came up from there.

Sorry for wasting your time.
