### ISSUE TITLE
@loadable/webpack-plugin chunk.name can be null

### ISSUE THREAD

**Issue by followbl** [smooth-code/loadable-components#137]
## 🐛 Bug Report

```js
// Disable splitChunks for loadable chunks
    compiler.options.optimization.splitChunks.chunks = function (chunk) {
      return !chunk.canBeInitial() && !chunk.name.startsWith('loadable-');
    };
```

## To Reproduce

1. CRA 2.5
2. Add SSR loadable-components
3. yarn run build
4. 
```js
TypeError: Cannot read property 'startsWith' of null
    at compiler.options.optimization.splitChunks.chunks (/example-application/node_modules/@loadable/webpack-plugin/lib/index.js:27:51)
    at getSelectedChunks (/example-application/node_modules/webpack/lib/optimize/SplitChunksPlugin.js:423:13)
    at compilation.hooks.optimizeChunksAdvanced.tap.chunks (/example-application/node_modules/webpack/lib/optimize/SplitChunksPlugin.js:584:13)
    at SyncBailHook.eval [as call] (eval at create (/example-application/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at SyncBailHook.lazyCompileHook (/example-application/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/example-application/node_modules/webpack/lib/Compilation.js:1208:38)
    at hooks.make.callAsync.err (/example-application/node_modules/webpack/lib/Compiler.js:547:17)
    at _done (eval at create (/example-application/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
    at _err2 (eval at create (/example-application/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:46:22)
    at tap.fn.args (/example-application/node_modules/react-dev-utils/ModuleNotFoundPlugin.js:114:15)
    at _addModuleChain (/example-application/node_modules/webpack/lib/Compilation.js:1065:12)
    at processModuleDependencies.err (/example-application/node_modules/webpack/lib/Compilation.js:981:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

## Expected behavior
discards chunks without a name...(I think that's what the expected behavior is)

**Comment by followbl** [comment]
@neoziro thank you for this repo and documentation, it's incredibly well written. I have a pretty complex CRA 2.0 + SSR (Streaming) application working perfect...this the final bug I'm running in to when running `yarn run build`

**Comment by followbl** [comment]
@neoziro I now know what happens here (or what I did wrong)...

**Incorrect**
```js
const Content = () => import('./container');
```

**Correct**
```js
const Content = loadable(() => import(/* webpackChunkName: "Content" */ './container'), {
  fallback: <LoadingContent />,
});
```

I know, I know, top is very wrong (and not even using loadable)...but in CRA 2.0 it did build fine without the webpack loadable plugin...I was thinking of something like...

```js
      if (!chunk.name) {
        throw new Error(`loadable: ensure you dont' have an un-named import (i.e. const Container = () => import('./container')) .`);
      }
```

let me know if you think this makes sense and I can make a PR, otherwise this can be closed 🎉

**Comment by neoziro** [comment]
In the new version, the webpack plugin will be mandatory for SSR (only static mode will be supported). So no, just let it like that for now.

But you will have to add this plugin 😅, without the manifest we can’t do anything.

**Comment by followbl** [comment]
your SSR streaming implementation is working perfectly for us now in production. very happy with our move to loadable-components 😺

**Comment by pristas-peter** [comment]
Hi, i still think that this should be fixed. I am using react-intl library, where I need to dynamically import locale data when bootstrapping client, so I am not using loadable components for this particular case. If i don't specify the magic comment with webpackChunkName the whole webpack process exits with error code. Code example:
```
const loadMyLocale = () => {
detect supported locale a then return import(`react-intl/locale-data/${locale}`)...
}

Promise.all([
    loadableReady(),
    loadMyLocale(),
]).then(() => ...)
```
