### ISSUE TITLE
@loadable/webpack-plugin TypeError: Cannot read property 'startsWith' of null

### ISSUE THREAD

**Issue by pristas-peter** [smooth-code/loadable-components#171]
## 🐛 Bug Report

Webpack's chunk name during compilation can be null, if you don't specify webpackChunkName magic comment during dynamic import()

```
Compiling...
/Users/peter/Developer/js/app/node_modules/react-scripts-extensions/node_modules/@loadable/webpack-plugin/lib/index.js:27
      return !chunk.canBeInitial() && !chunk.name.startsWith('loadable-');
                                                  ^

TypeError: Cannot read property 'startsWith' of null
    at compiler.options.optimization.splitChunks.chunks (/Users/peter/Developer/js/app/node_modules/react-scripts-extensions/node_modules/@loadable/webpack-plugin/lib/index.js:27:51)
    at getSelectedChunks (/Users/peter/Developer/js/app/node_modules/webpack/lib/optimize/SplitChunksPlugin.js:423:13)
    at compilation.hooks.optimizeChunksAdvanced.tap.chunks (/Users/peter/Developer/js/app/node_modules/webpack/lib/optimize/SplitChunksPlugin.js:584:13)
    at SyncBailHook.eval [as call] (eval at create (/Users/peter/Developer/js/app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at SyncBailHook.lazyCompileHook (/Users/peter/Developer/js/app/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/Users/peter/Developer/js/app/node_modules/webpack/lib/Compilation.js:1208:38)
    at hooks.make.callAsync.err (/Users/peter/Developer/js/app/node_modules/webpack/lib/Compiler.js:547:17)
    at _done (eval at create (/Users/peter/Developer/js/app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:11:1)
    at _err1 (eval at create (/Users/peter/Developer/js/app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:34:22)
    at tap.fn.args (/Users/peter/Developer/js/app/node_modules/react-dev-utils/ModuleNotFoundPlugin.js:114:15)
    at _addModuleChain (/Users/peter/Developer/js/app/node_modules/webpack/lib/Compilation.js:1065:12)
    at processModuleDependencies.err (/Users/peter/Developer/js/app/node_modules/webpack/lib/Compilation.js:981:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error Command failed with exit code 1.
``` 

## To Reproduce

Install create react app v2. Eject. Add this plugin to webpack's config.

index.js
```
import React from 'react';
import {addLocaleData} from 'react-intl';
import ReactDOM from 'react-dom';
import { loadableReady } from '@loadable/component';
import './index.css';
import * as serviceWorker from './serviceWorker';


Promise.all([
    import('react-intl/locale-data/sk'), //  <-- works when  import(/* webpackChunkName: "foo" */ 'react-intl/locale-data/sk')
    loadableReady(),
])
    .then(([locale]) => {
        addLocaleData(locale.default);
        ReactDOM.render(<App />, document.getElementById('root'));
    })

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: http://bit.ly/CRA-PWA
serviceWorker.unregister();
```

## Expected behavior
```
return !chunk.canBeInitial() && !(chunk.name && chunk.name.startsWith('loadable-'));
```
## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash

```

**Comment by neoziro** [comment]
Hello @pristas-peter, can you provide a repro repository? I am sorry but I can't reproduce the bug, I don't have enough information.

**Comment by pristas-peter** [comment]
I'm so sorry bro, the problem was on my side. Somehow node_modules folder got published into my private package where there was v4 of this plugin. Removed the folder and everything works. Spent quite a few hours with this, I hate npm and all this package ecosystem, f**k...

You can close this issue.

**Comment by neoziro** [comment]
Good news!
