### ISSUE TITLE
Cannot find chunk in stats

### ISSUE THREAD

**Issue by nandosangenetto** [smooth-code/loadable-components#248]
## 🐛 Bug Report

I'm having a problem similar to the #216 problem. I run webpack and it gets all chunks, but the server cannot find the chunk in the stats json.

My `babel.config.js` is:
```javascript
function isWebTarget(caller) {
  return Boolean(caller && caller.target === 'web');
}

function isWebpack(caller) {
  return Boolean(caller && caller.name === 'babel-loader');
}

module.exports = api => {
  const web = api.caller(isWebTarget);
  const webpack = api.caller(isWebpack);

  return {
    presets: [
      '@babel/preset-react',
      [
        '@babel/preset-env',
        {
          useBuiltIns: web ? 'entry' : undefined,
          targets: !web ? { node: 'current' } : undefined,
          modules: webpack ? false : 'commonjs',
        },
      ],
    ],
    plugins: [
      '@babel/transform-runtime',
      '@babel/transform-async-to-generator',
      '@babel/proposal-class-properties',
      'babel-plugin-dynamic-import-webpack',
      '@loadable/babel-plugin',
      'styled-components',
    ].filter(Boolean),
  };
};
```

I've tried to reorder the plugins and adding `@babel/plugin-syntax-dynamic-import` which doesn't change anything. If I remove the `babel-plugin-dynamic-import-webpack` my app doesn't build.

And following the config above I was able to successfully build the project but when someone try to access the server, I get this error:

```
>>> Req.path:  /
(node:23605) UnhandledPromiseRejectionWarning: Invariant Violation: loadable: cannot find components-HomePage in stats
    at invariant (/Users/nando.sangenetto/Sites/reverb-web/node_modules/@loadable/component/dist/loadable.cjs.js:13:15)
    at ChunkExtractor.getChunkGroup (/Users/nando.sangenetto/Sites/reverb-web/node_modules/@loadable/server/lib/ChunkExtractor.js:175:36)
    at one (/Users/nando.sangenetto/Sites/reverb-web/node_modules/@loadable/server/lib/ChunkExtractor.js:246:31)
    at arrayMap (/Users/nando.sangenetto/Sites/reverb-web/node_modules/lodash/lodash.js:639:23)
    at map (/Users/nando.sangenetto/Sites/reverb-web/node_modules/lodash/lodash.js:9556:14)
    at Function.flatMap (/Users/nando.sangenetto/Sites/reverb-web/node_modules/lodash/lodash.js:9259:26)
    at ChunkExtractor.getChunkDependencies (/Users/nando.sangenetto/Sites/reverb-web/node_modules/@loadable/server/lib/ChunkExtractor.js:252:51)
    at ChunkExtractor.getRequiredChunksScriptContent (/Users/nando.sangenetto/Sites/reverb-web/node_modules/@loadable/server/lib/ChunkExtractor.js:259:100)
    at ChunkExtractor.getRequiredChunksScriptElement (/Users/nando.sangenetto/Sites/reverb-web/node_modules/@loadable/server/lib/ChunkExtractor.js:270:22)
    at ChunkExtractor.getScriptElements (/Users/nando.sangenetto/Sites/reverb-web/node_modules/@loadable/server/lib/ChunkExtractor.js:332:38)
(node:23605) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23605) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:
```
## System:
 - OS: macOS 10.14.1
 - CPU: (8) x64 Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
 - Memory: 86.00 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 11.10.0 - /usr/local/bin/node
 - Yarn: 1.7.0 - /usr/local/bin/yarn
 - npm: 6.8.0 - ~/Sites/reverb-web/node_modules/.bin/npm
## npmPackages:
 - @loadable/babel-plugin: ^5.6.0 => 5.6.0
 - @loadable/component: ^5.6.0 => 5.6.0
 - @loadable/server: ^5.6.0 => 5.6.0
 - @loadable/webpack-plugin: ^5.5.0 => 5.5.0
```

**Comment by neoziro** [comment]
Hello @nandosangenetto, your problem is `babel-plugin-dynamic-import-webpack`. It could not work with it. Be sure to use the latest version of webpack. webpack understand dynamic imports so you don't need this babel plugin.

First you have to figure out why it doesn't work without this plugin. I close this issue because it is webpack issue, not a loadable issue.

**Comment by lostpebble** [comment]
Hi @gregberge , thanks for this great library!

Just thought I'd drop a line here to say that this was a big confusion for me today, and an indication in the docs about `babel-plugin-dynamic-import-webpack` not being necessary or compatible would have gone a long way. As soon as I took it out, everything was smooth as butter!

Made a PR, if you think its a good change. (https://github.com/gregberge/loadable-components/pull/664)
