### ISSUE TITLE
Chunk name mismatch for dynamic child directory import

### ISSUE THREAD

**Issue by akagomez** [smooth-code/loadable-components#331]
### 🐛 Bug Report

Dynamic imports without a static directory name result in mismatched chunk names.

A reproduction of https://github.com/smooth-code/loadable-components/issues/220

### To Reproduce

Import a file dynamically relative to the current module in a directly descendant child directory: 

```
loadable(props => import(`./${props.letter}/file`))
```

### Expected behavior

The chunk name created at build time should match the chunk name referenced at runtime. 

### Link to repl or repo (highly encouraged)

1. [Clone the forked loadable-components repo](https://github.com/akagomez/loadable-components)
1. Checkout the branch `chunk-name-mismatch-bug`
1. Run `yarn install && yarn run build`, 
1. Navigate to `examples/server-side-rendering`
1. Run `yarn install`
1. Run the example: 

    ```bash
    $ yarn run dev
    yarn run v1.13.0
    $ nodemon src/server/main.js
    [nodemon] 1.19.0
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: *.*
    [nodemon] starting `babel-node src/server/main.js`
    Server started http://localhost:9000
    ```

1. Navigate to `localhost:9000` in a browser and observe the error:

    ```
    Invariant Violation: loadable: cannot find G-file in stats
        at invariant (/Users/akagomez/Code/smooth-code/loadable-components/packages/component/dist/loadable.cjs.js:13:15)
        at ChunkExtractor.getChunkGroup (/Users/akagomez/Code/smooth-code/loadable-components/packages/server/lib/ChunkExtractor.js:188:36)
        at one (/Users/akagomez/Code/smooth-code/loadable-components/packages/server/lib/ChunkExtractor.js:211:31)
        at chunk (/Users/akagomez/Code/smooth-code/loadable-components/packages/server/lib/ChunkExtractor.js:38:70)
        at arrayMap (/Users/akagomez/Code/smooth-code/loadable-components/node_modules/lodash/_arrayMap.js:16:21)
        at map (/Users/akagomez/Code/smooth-code/loadable-components/node_modules/lodash/map.js:50:10)
        at flatMap (/Users/akagomez/Code/smooth-code/loadable-components/node_modules/lodash/flatMap.js:26:22)
        at getAssets (/Users/akagomez/Code/smooth-code/loadable-components/packages/server/lib/ChunkExtractor.js:38:52)
        at ChunkExtractor.getChunkAssets (/Users/akagomez/Code/smooth-code/loadable-components/packages/server/lib/ChunkExtractor.js:221:14)
        at ChunkExtractor.getMainAssets (/Users/akagomez/Code/smooth-code/loadable-components/packages/server/lib/ChunkExtractor.js:304:25)
    ```

1. Confirm the chunk name referenced at runtime is missing from the build: 

    ```bash
    $ ls public/dist/node/
    G-file-file.js      letters-A-css.js    letters-A.js        letters-C.js        letters-E.js        letters-Z-file.js   main.css
    letters-A-css.css   letters-A.css       letters-B.js        letters-D.js        letters-F.js        loadable-stats.json main.js
    ```
1. Confirm the chunk name referenced at runtime is missing from `loadable-stats.json`:

    ```bash
    $ grep G-file public/dist/web/loadable-stats.json
        "G-file-file": "G-file-file.js",
          "name": "G-file-file.js",
            "G-file-file"
            "G-file-file"
        "G-file-file": {
            "G-file-file"
            "G-file-file.js"
    ```

**Comment by neoziro** [comment]
Hello @akagomez, I will check it, thanks for the detailed issue!
