### ISSUE TITLE
@loadable/babel-plugin Error

### ISSUE THREAD

**Issue by Greatwallycc** [smooth-code/loadable-components#413]
Before installing @loadable/babel-plugin,here is the error:

Invariant Violation: loadable: SSR requires `@loadable/babel-plugin`, please install it
    at invariant (D:\学习\React\EDS\node_modules\@loadable\component\dist\loadable.cjs.js:17:15)
    at new InnerLoadable (D:\学习\React\EDS\node_modules\@loadable\component\dist\loadable.cjs.js:116:9)
    at processChild (D:\学习\React\EDS\node_modules\react-dom\cjs\react-dom-server.node.development.js:2846:14)
    at resolve (D:\学习\React\EDS\node_modules\react-dom\cjs\react-dom-server.node.development.js:2812:5)
    at ReactDOMServerRenderer.render (D:\学习\React\EDS\node_modules\react-dom\cjs\react-dom-server.node.development.js:3202:22)
    at ReactDOMServerRenderer.read (D:\学习\React\EDS\node_modules\react-dom\cjs\react-dom-server.node.development.js:3161:29)
    at ReactMarkupReadableStream._read (D:\学习\React\EDS\node_modules\react-dom\cjs\react-dom-server.node.development.js:3698:38)
    at ReactMarkupReadableStream.Readable.read (_stream_readable.js:470:10)
    at resume_ (_stream_readable.js:949:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE

so I install it,and then,there is another error:

ERROR in ./routes/index.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
TypeError: Property value expected type of string but got null
at Object.validate (D:\学习\React\EDS\node_modules@babel\types\lib\definitions\utils.js:164:13)
at validateField (D:\学习\React\EDS\node_modules@babel\types\lib\validators\validate.js:22:9)
at validate (D:\学习\React\EDS\node_modules@babel\types\lib\validators\validate.js:16:3)
at builder (D:\学习\React\EDS\node_modules@babel\types\lib\builders\builder.js:46:27)
at Object.StringLiteral (D:\学习\React\EDS\node_modules@babel\types\lib\builders\generated\index.js:335:31)
at getCallValue (D:\学习\React\EDS\node_modules@loadable\babel-plugin\lib\properties\resolve.js:27:14)
at D:\学习\React\EDS\node_modules@loadable\babel-plugin\lib\properties\resolve.js:34:9
at t.objectExpression.propertyFactories.map.getProperty (D:\学习\React\EDS\node_modules@loadable\babel-plugin\lib\index.js:90:76)
at Array.map ()
at transformImport (D:\学习\React\EDS\node_modules@loadable\babel-plugin\lib\index.js:90:57)
at PluginPass.CallExpression (D:\学习\React\EDS\node_modules@loadable\babel-plugin\lib\index.js:108:9)
at newFn (D:\学习\React\EDS\node_modules@babel\traverse\lib\visitors.js:193:21)
at NodePath._call (D:\学习\React\EDS\node_modules@babel\traverse\lib\path\context.js:53:20)
at NodePath.call (D:\学习\React\EDS\node_modules@babel\traverse\lib\path\context.js:40:17)
at NodePath.visit (D:\学习\React\EDS\node_modules@babel\traverse\lib\path\context.js:88:12)
at TraversalContext.visitQueue (D:\学习\React\EDS\node_modules@babel\traverse\lib\context.js:118:16)
@ ./ssr/SSR.js 18:0-31 33:49-55
@ ./ssr/server.js

I can't find the reason,help me,thanks.

**Comment by neoziro** [comment]
Hello @Greatwallycc, I am sorry I can't help you, there is no enough details.
