### ISSUE TITLE
Accessing Route Config from within server.js file

### ISSUE THREAD

**Issue by ctwh** [smooth-code/loadable-components#429]
Hi there,

I am trying to use the examples/server-side-rendering application to also account for data prefetching within the server/main.js file.  

The goal is:

1. Extract the route from Express' `res.path`.
2. Match it against react-router-config's [matchRoute()](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config#matchroutesroutes-pathname)
3. Develop an array of promises that have loadData() functions for the matched route(s)
4. Once complete, set the data to the Redux Store.  
5. `renderToString` renders with the store data set accordingly.

Using the example application, I get an error when server/main.js references Routes.js because of the css files associated to the components of each route:

.App {
^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/Users/whanson/Documents/CapTech/Personal/Workspaces/loadable-components/loadable-components/examples/server-side-rendering/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/whanson/Documents/CapTech/Personal/Workspaces/loadable-components/loadable-components/examples/server-side-rendering/src/client/my-app/App.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

I can see that webpack is building properly; this appears to happen when running **npm run dev**

Any help would be great.  Thanks!

**Comment by neoziro** [comment]
Hello, you have to build your server-side bundle with webpack. This problem is not relative to loadable-components.
