### ISSUE TITLE
Document is not defined with SSR and Redux

### ISSUE THREAD

**Issue by KrustyC** [smooth-code/loadable-components#70]
I have this code
```
const store = createStore()

  const promises = matchRoutes(routes, req.url).map(({ route, match }) => {
    const { fetchData } = route.component
    return fetchData instanceof Function ? store.dispatch(fetchData(match)) : Promise.resolve(null)
  })

  Promise.all(promises).then(() => {
    const context = {}
    const appWithRouter = (
      <Provider store={store}>
        <StaticRouter location={req.url} context={context}>
          {renderRoutes(routes)}
        </StaticRouter>
      </Provider>
    )
  
    if (context.url) {
      return res.redirect(context.url)
    }

    getLoadableState(appWithRouter).then(loadableState => {
      const html = ReactDOMServer.renderToString(appWithRouter)
      renderApp(res, store, {}, req.url, html, loadableState)
    }).catch(err => {
      return res.status(500).end('Internal Server Error')
    })
  })
```

Which works fine when I'm not dispatching anything to redux store.

so in this function here
```
const promises = matchRoutes(routes, req.url).map(({ route, match }) => {
    const { fetchData } = route.component
    return fetchData instanceof Function ? store.dispatch(fetchData(match)) : Promise.resolve(null)
  })
```
if my component doesn't fetch any data, then al works fine, but if it doesn fetch data, then the `getLoadableState` fails returning this: 
```
ReferenceError: document is not defined
    at Parser.createDocument (/home/davidec/Documents/sites/muso/webapp/node_modules/interweave/lib/Parser.js:217:41)
    at new Parser (/home/davidec/Documents/sites/muso/webapp/node_modules/interweave/lib/Parser.js:69:21)
    at Interweave.parseMarkup (/home/davidec/Documents/sites/muso/webapp/node_modules/interweave/lib/Interweave.js:100:20)
    at Interweave.render (/home/davidec/Documents/sites/muso/webapp/node_modules/interweave/lib/Interweave.js:133:14)
    at walkTree (/home/davidec/Documents/sites/muso/webapp/node_modules/loadable-components/src/server/index.js:83:26)
    at /home/davidec/Documents/sites/muso/webapp/node_modules/loadable-components/dist/loadable-components.server.cjs.js:158:13
    at forEachSingleChild (/home/davidec/Documents/sites/muso/webapp/node_modules/react/cjs/react.development.js:849:8)
    at traverseAllChildrenImpl (/home/davidec/Documents/sites/muso/webapp/node_modules/react/cjs/react.development.js:753:5)
    at traverseAllChildrenImpl (/home/davidec/Documents/sites/muso/webapp/node_modules/react/cjs/react.development.js:769:23)
    at traverseAllChildren (/home/davidec/Documents/sites/muso/webapp/node_modules/react/cjs/react.development.js:824:10)
    at Object.forEachChildren [as forEach] (/home/davidec/Documents/sites/muso/webapp/node_modules/react/cjs/react.development.js:869:3)
    at walkTree (/home/davidec/Documents/sites/muso/webapp/node_modules/loadable-components/src/server/index.js:120:24)
    at walkTree (/home/davidec/Documents/sites/muso/webapp/node_modules/loadable-components/dist/loadable-components.server.cjs.js:133:11)
    at /home/davidec/Documents/sites/muso/webapp/node_modules/loadable-components/dist/loadable-components.server.cjs.js:158:13
    at forEachSingleChild (/home/davidec/Documents/sites/muso/webapp/node_modules/react/cjs/react.development.js:849:8)
    at traverseAllChildrenImpl (/home/davidec/Documents/sites/muso/webapp/node_modules/react/cjs/react.development.js:753:5)
```

I can't figure out wha tthe problem is...

**Comment by neoziro** [comment]
I think the problem is relative to [interweave](https://github.com/milesj/interweave#server-side-rendering). I don't think it is relative to Loadable Components.
